name: Android Coverage Test
permissions:
  contents: read


on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Run Tests with Coverage
        run: ./gradlew testDebugUnitTestCoverage jacocoTestReport

      - name: Check Coverage Threshold (70%)
        run: ./gradlew checkCoverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/
