name: Android Coverage Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Run Tests with Coverage
        run: ./gradlew testDebugUnitTestCoverage jacocoTestReport

      - name: Check Coverage Threshold (70%)
        run: ./gradlew checkCoverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html/
