name: Android Coverage and E2E Tests

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests with Coverage
        run: ./gradlew testDebugUnitTestCoverage jacocoTestReport

      - name: Check Coverage Threshold (70%)
        run: ./gradlew checkCoverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/
