name: Android Coverage and E2E Tests

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests with Coverage
        run: ./gradlew testDebugUnitTestCoverage jacocoTestReport

      - name: Check Coverage Threshold (70%)
        run: ./gradlew checkCoverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/

  e2e-tests:
    name: Run Instrumented E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Run E2E Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-boot-timeout: 600
          disable-animations: true
          emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
          script: ./gradlew connectedDebugAndroidTest

